const { test, mock } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

const modulePromise = import('../api/track-order.js');
const adminPromise = import('../api/_lib/shopify-admin.js');
process.env.SHOPIFY_STORE_DOMAIN = 'fixture.myshopify.com';
process.env.SHOPIFY_ADMIN_CLIENT_ID = 'fixture-client';
process.env.SHOPIFY_ADMIN_CLIENT_SECRET = 'fixture-secret';

function response() { return { statusCode: 0, body: null, headers: {}, setHeader(k, v) { this.headers[k] = v; }, status(n) { this.statusCode = n; return this; }, json(v) { this.body = v; return this; } }; }
function order(overrides = {}) { return { id: 'gid://shopify/Order/1', name: '#1001', number: 1001, createdAt: '2026-09-22T10:00:00Z', processedAt: '2026-09-22T10:00:00Z', email: 'Customer@Example.com', customer: { email: null }, cancelledAt: null, displayFinancialStatus: 'PAID', displayFulfillmentStatus: 'UNFULFILLED', returnStatus: 'NO_RETURN', currentTotalPriceSet: { shopMoney: { amount: '4199.00', currencyCode: 'INR' } }, totalReceivedSet: { shopMoney: { amount: '4199.00', currencyCode: 'INR' } }, totalRefundedSet: { shopMoney: { amount: '0.00', currencyCode: 'INR' } }, transactionsCount: { count: 1, precision: 'EXACT' }, transactions: [{ kind: 'SALE', status: 'SUCCESS' }], lineItems: { nodes: [{ title: 'Aura Whey Mawa Kulfi', quantity: 2 }] }, fulfillments: [], fulfillmentOrders: { pageInfo: { hasNextPage: false }, nodes: [{ status: 'OPEN', requestStatus: 'UNSUBMITTED' }] }, ...overrides }; }
function installShopify(t, shopifyOrder) { let calls = []; adminPromise.then(({ clearAdminTokenCache }) => clearAdminTokenCache()); t.mock.method(global, 'fetch', async (url, options) => { calls.push({ url, options }); if (url.includes('/oauth/')) return { ok: true, status: 200, json: async () => ({ access_token: 'fixture-admin-token', expires_in: 3600 }) }; return { ok: true, status: 200, json: async () => ({ data: { orders: { nodes: [shopifyOrder] } } }) }; }); return calls; }

test('normalizes 1001, #1001 and AW-1001', async () => { const { normalizeOrderNumber } = await modulePromise; assert.equal(normalizeOrderNumber('1001'), '1001'); assert.equal(normalizeOrderNumber('#1001'), '1001'); assert.equal(normalizeOrderNumber(' AW-1001 '), '1001'); assert.equal(normalizeOrderNumber('one'), null); });

test('correct order and case-insensitive email return a safe order payload', async t => { const { findTrackOrder } = await modulePromise; installShopify(t, order()); const result = await findTrackOrder({ orderNumber: '#1001', email: ' customer@example.COM ' }); assert.equal(result.orderNumber, '#1001'); assert.equal(result.total, '4199.00'); assert.equal(result.products[0].quantity, 2); assert.equal(result.email, undefined); assert.equal(result.customer, undefined); assert.equal(JSON.stringify(result).includes('Customer@Example.com'), false); });

test('incorrect email and nonexistent order return the same generic response', async t => { const { default: handler } = await modulePromise; installShopify(t, order()); const wrong = response(); await handler({ method: 'POST', body: { orderNumber: '1001', email: 'wrong@example.com' } }, wrong); const missing = response(); t.mock.method(global, 'fetch', async (url) => url.includes('/oauth/') ? ({ ok: true, status: 200, json: async () => ({ access_token: 'token-2', expires_in: 3600 }) }) : ({ ok: true, status: 200, json: async () => ({ data: { orders: { nodes: [] } } }) })); await handler({ method: 'POST', body: { orderNumber: '9999', email: 'wrong@example.com' } }, missing); assert.equal(wrong.statusCode, 404); assert.equal(missing.statusCode, 404); assert.deepEqual(wrong.body, missing.body); });

test('malformed input is rejected without a Shopify lookup', async t => { const { default: handler } = await modulePromise; const calls = []; t.mock.method(global, 'fetch', async (...args) => { calls.push(args); return { ok: true, status: 200, json: async () => ({}) }; }); const result = response(); await handler({ method: 'POST', body: { orderNumber: '#x', email: 'not-an-email' } }, result); assert.equal(result.statusCode, 400); assert.equal(calls.length, 0); });

test('fulfilled orders expose progress and multiple tracking entries', async t => { const { findTrackOrder } = await modulePromise; installShopify(t, order({ displayFulfillmentStatus: 'FULFILLED', fulfillments: [{ displayStatus: 'IN_TRANSIT', status: 'SUCCESS', trackingInfo: [{ company: 'DHL', number: 'D1', url: 'https://dhl.example/1' }, { company: 'DHL', number: 'D2', url: 'https://dhl.example/2' }] }] })); const result = await findTrackOrder({ orderNumber: 'AW-1001', email: 'customer@example.com' }); assert.equal(result.progress, 'shipped'); assert.equal(result.tracking.length, 2); assert.equal(result.tracking[0].number, 'D1'); assert.equal(result.preparing, false); });

test('Shopify failure is generic and safe', async t => { const { default: handler } = await modulePromise; t.mock.method(global, 'fetch', async () => ({ ok: false, status: 500, json: async () => ({ secret: 'hidden' }) })); const result = response(); await handler({ method: 'POST', body: { orderNumber: '1001', email: 'customer@example.com' } }, result); assert.equal(result.statusCode, 502); assert.equal(result.body.message, 'Order tracking is temporarily unavailable.'); assert.equal(JSON.stringify(result.body).includes('hidden'), false); });

test('frontend calls Track Order and exposes cancellation only through confirmation modal', () => { const app = fs.readFileSync('app.js', 'utf8'); assert.match(app, /fetch\('\/api\/track-order'/); assert.doesNotMatch(app, /order === 'AW-1001'/); assert.match(app, /data-track-cancel/); assert.match(app, /Cancel order \$\{escapeHtml\(order\.orderNumber\)\}\?/); assert.match(app, /fetch\('\/api\/track-order\/cancel'/); assert.match(app, /if \(busy \|\| !form\.reportValidity\(\)\) return/); assert.match(app, /ORDER CANCELLED/); assert.match(app, /cancellation\.eligible[\s\S]*data-track-cancel/); assert.doesNotMatch(app, /data-track-cancel[^>]*data-action/); });

test('cancelled/refunded lookup renders final state without an active cancellation button', async t => { const { findTrackOrder } = await modulePromise; installShopify(t, order({ cancelledAt: '2026-09-24T10:30:00Z', displayFinancialStatus: 'REFUNDED', displayFulfillmentStatus: 'UNFULFILLED' })); const result = await findTrackOrder({ orderNumber: '1001', email: 'customer@example.com' }); assert.equal(result.cancelled, true); assert.equal(result.paymentStatus, 'REFUNDED'); assert.equal(result.cancellation.eligible, false); assert.equal(result.cancellation.code, 'already_cancelled'); });
