import { assets, documents, faqs, posts, productPrice } from '../data/catalog.js';
import { icon } from '../components/ui/icons.js';
import { Accordion } from '../components/ui/Accordion.js';
import { BlogCard } from '../components/ui/BlogCard.js';
import { CouponForm } from '../components/ui/CouponForm.js';
import { ProductCard } from '../components/ui/ProductCard.js';
import { button, image, routeLink } from '../components/ui/render.js';

function documentCard([title, type, detail]) {
  return `<article class="card document-card"><div class="document-icon">${icon('file')}</div><p class="document-type">${type}</p><h3>${title}</h3><p>${detail}</p>${button(`view-document-${title}`, 'View document', 'document-button')}</article>`;
}

export function ShopPage(state) {
  const tabContent = {
    Details: 'Aura Whey Protein is supplied in a 1 kg pack with two flavour options: Mawa Kulfi and Rich Chocolate. Choose a flavour, add it to your cart, and complete payment through the Shopify checkout.',
    Nutrition: 'Per 35 g serving: 24 g protein and 5.7 g BCAAs. One 1 kg pack contains 28 servings. Refer to the pack nutrition panel for the complete information.',
    Ingredients: 'Refer to the product pack for the ingredients list, allergen advice, storage instructions, and full nutritional information.'
  };
  const productImage = state.flavour === 'Mawa Kulfi' ? assets.mawa : assets.chocolate;
  return `<h1 class="page-title">Aura Whey Protein</h1><div class="product-layout"><section class="product-gallery"><div class="product-main-image">${image(productImage, `${state.flavour} Aura Whey product`)}</div><div class="thumbnail-row"><button type="button" class="thumbnail" data-action="select-Mawa Kulfi" aria-label="Select Mawa Kulfi">${image(assets.mawa, 'Mawa Kulfi')}</button><button type="button" class="thumbnail" data-action="select-Rich Chocolate" aria-label="Select Rich Chocolate">${image(assets.chocolate, 'Rich Chocolate')}</button><div class="thumbnail">${icon('file')}<span>Label</span></div></div></section><section class="purchase-panel"><p class="breadcrumb">Shop / Whey protein</p><h2>Aura Whey <span>${state.flavour}</span></h2><div class="price">${productPrice}<span>Inclusive of taxes</span></div><p>1 kg · 28 servings · 35 g serving size</p><div class="flavour-picker"><span>Choose flavour</span><div class="button-row"><button type="button" class="flavour ${state.flavour === 'Mawa Kulfi' ? 'active' : ''}" data-action="select-Mawa Kulfi">Mawa Kulfi</button><button type="button" class="flavour ${state.flavour === 'Rich Chocolate' ? 'active' : ''}" data-action="select-Rich Chocolate">Rich Chocolate</button></div></div><div class="coupon-entry">${CouponForm(state)}</div><div class="product-actions"><div class="button-row">${button('add-cart', 'Add to cart', 'primary', 'bag')}${routeLink('quality', 'View quality documents', 'button-link secondary')}</div></div></section></div><section class="section"><div class="section-inner"><div class="tab-list">${Object.keys(tabContent).map(tab => `<button type="button" class="tab ${state.tab === tab ? 'active' : ''}" data-action="tab-${tab}">${tab}</button>`).join('')}</div><div class="tab-panel">${tabContent[state.tab]}</div></div></section><section class="section"><div class="section-inner"><div class="trust-grid"><div class="trust-item"><strong>Manufacturing</strong><span>GMP-certified facility</span></div><div class="trust-item"><strong>Food safety</strong><span>ISO 22000 and HACCP documents</span></div><div class="trust-item"><strong>Authenticity</strong><span>${routeLink('authenticate', 'Authenticate your pack')}</span></div><div class="trust-item"><strong>Need help?</strong><span>${routeLink('faq', 'Read the FAQs')}</span></div></div></div></section>`;
}

function totals(state) {
  const subtotal = 4199 * state.quantity;
  const discount = state.coupon === 'DISC5' ? Math.round(subtotal * .05) : 0;
  return { subtotal, discount, total: subtotal - discount, format: value => `₹${value.toLocaleString('en-IN')}` };
}

export function CartPage(state) {
  if (!state.cart) return `<section class="empty-state"><div><p class="hero-overline">Your cart</p><h1>Nothing here yet.</h1><p>Pick a flavour to begin your Aura Whey routine.</p>${routeLink('shop', 'Shop whey protein', 'button-link primary')}</div></section>`;
  const amount = totals(state);
  const productImage = state.flavour === 'Mawa Kulfi' ? assets.mawa : assets.chocolate;
  return `<h1 class="page-title">Your cart</h1><div class="cart-layout"><section><article class="cart-item"><div class="cart-image">${image(productImage, `Aura Whey ${state.flavour}`)}</div><div><h2>Aura Whey ${state.flavour}</h2><p>1 kg · 28 servings</p><strong class="item-price">${productPrice}</strong><div class="quantity"><span>Quantity</span><button class="quantity-button" type="button" data-action="quantity-down" aria-label="Decrease quantity">−</button><span>${state.quantity}</span><button class="quantity-button" type="button" data-action="quantity-up" aria-label="Increase quantity">+</button></div></div>${button('remove-cart', 'Remove')}</article></section><aside class="summary"><h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><span>${amount.format(amount.subtotal)}</span></div>${amount.discount ? `<div class="summary-row discount"><span>DISC5</span><span>−${amount.format(amount.discount)}</span></div>` : ''}<div class="summary-row"><span>Shipping</span><span>Calculated at checkout</span></div><div class="summary-row"><strong>Total</strong><strong>${amount.format(amount.total)}</strong></div><div class="cart-coupon">${CouponForm(state)}</div><p>${button('checkout', 'Secure checkout', 'primary')}</p><p class="small">Checkout is completed securely through Shopify.</p></aside></div>`;
}

export function CheckoutPage() { return `<section class="handoff"><div class="handoff-icon">${icon('bag')}</div><p class="hero-overline">Secure checkout</p><h1>Ready for Shopify checkout.</h1><p>Your delivery address, payment method, taxes, and order confirmation are handled in the secure Shopify checkout.</p><div class="button-row">${routeLink('cart', 'Back to cart', 'button-link')}${button('shopify-checkout', 'Continue to checkout', 'primary')}</div><div id="checkout-result" aria-live="polite"></div></section>`; }

export function QualityPage() { return `<section class="page-intro"><p class="hero-overline">Quality & documentation</p><h1>Quality you can inspect.</h1><p>Browse the supplied food-safety and manufacturing documents, then authenticate the code on your pack.</p></section><section class="section"><div class="section-inner"><div class="section-head"><div><h2>Certificates</h2><div class="gold-rule"></div></div><p>Food safety, manufacturing, and dietary certification documents.</p></div><div class="grid grid-3">${documents.map(documentCard).join('')}</div></div></section><section class="section"><div class="section-inner quality-process"><div class="quality-process-image">${image(assets.labelMawa, 'Aura Whey product nutrition information')}</div><div><h2>Read the pack first.</h2><p>Nutrition, ingredients, allergen advice, and storage guidance are printed on the product label. We keep the supplied certificates alongside it for straightforward review.</p><div class="button-row">${routeLink('authenticate', 'Authenticate your pack', 'button-link primary')}${routeLink('contact', 'Contact support', 'button-link')}</div></div></div></section>`; }

export function SearchPage(state) {
  const query = state.searchQuery.trim();
  const results = query ? `<div class="search-results"><p>Showing matches for <strong>${query}</strong></p><div class="grid grid-2">${ProductCard('Mawa Kulfi')}${ProductCard('Rich Chocolate')}</div></div>` : '<p class="search-help">Search for a product, a quality document, or a journal guide.</p>';
  return `<section class="page-intro compact"><p class="hero-overline">Search</p><h1>Find what you need.</h1><form class="search-form" data-form="search"><label class="sr-only" for="store-search">Search the store</label><input id="store-search" name="query" value="${query}" placeholder="Search products and guides" />${button('submit-search', 'Search', 'primary', 'search')}</form>${results}</section>`;
}

export function AccountPage() { return `<section class="page-intro compact"><p class="hero-overline">Your account</p><h1>Sign in to Aura Whey.</h1><div class="account-layout"><form class="form" data-form="account"><label class="field">Email address<input name="email" type="email" placeholder="you@example.com" /></label><label class="field">Password<input name="password" type="password" placeholder="Your password" /></label>${button('submit-account', 'Sign in', 'primary')}</form><div class="account-aside"><h3>New here?</h3><p>Create your customer account during Shopify checkout. You can then return to view your orders.</p>${routeLink('track-order', 'Track an order instead', 'text-link')}</div></div><div id="account-result" aria-live="polite"></div></section>`; }

export function BlogPage() { return `<section class="page-intro"><p class="hero-overline">Aura journal</p><h1>Train with clarity.</h1><p>Practical reads for choosing your product and making your routine easier to keep.</p></section><section class="section"><div class="featured-post"><div class="featured-image">${image(posts[0].image, posts[0].title)}</div><div><p class="hero-overline">Featured guide</p><h2>${posts[0].title}</h2><p>${posts[0].excerpt}</p>${routeLink('article', 'Read the guide', 'button-link primary')}</div></div></section><section class="section"><div class="section-inner"><div class="grid grid-3">${[0, 1, 2, 0, 1, 2].map(BlogCard).join('')}</div></div></section>`; }

export function ArticlePage() { return `<article class="article"><p>${routeLink('blog', 'Back to journal', 'text-link')}</p><p class="hero-overline">Product guide</p><h1>How to choose a whey protein flavour</h1><p class="article-meta">Aura Whey Journal · 5 minute read</p><div class="article-hero">${image(assets.duo, 'Aura Whey product flavours')}</div><div class="article-layout"><div><h2>Start with the flavour you will use.</h2><p>The best choice is usually the flavour that makes your everyday shake easy to enjoy. Rich Chocolate keeps things familiar, while Mawa Kulfi brings a creamier, dessert-inspired profile.</p><h2>Keep your routine simple.</h2><p>Use the product label as your reference for serving size, nutrition information, ingredients, and allergen guidance. Consistency is easier when the plan is clear.</p></div><aside class="article-aside"><strong>Explore Aura Whey</strong>${routeLink('shop', 'Shop both flavours', 'text-link')}${routeLink('quality', 'View quality documents', 'text-link')}</aside></div></article>`; }

export function AuthenticatePage() { return `<section class="page-intro compact"><p class="hero-overline">Product authentication</p><h1>Check your Aura Whey pack.</h1><div class="verify-layout"><div class="verify-image">${image(assets.labelMawa, 'Aura Whey pack label')}</div><div><p>Enter the authentication code printed on your pack. For this interactive preview, use <strong>AURA-2026-001</strong> or <strong>AURA-2026-USED</strong>.</p><form class="form" data-form="authenticate"><label class="field">Pack code<input name="code" placeholder="Enter pack code" /></label>${button('verify-code', 'Verify code', 'primary', 'check')}</form><div id="auth-result" aria-live="polite"></div></div></div></section>`; }

export function TrackOrderPage() { return `<section class="page-intro compact"><p class="hero-overline">Order tracking</p><h1>Where is your order?</h1><div class="track-layout"><div><form class="form" data-form="tracking"><label class="field">Order number<input name="order" placeholder="e.g. AW-1001" /></label><label class="field">Email address<input name="email" type="email" placeholder="Email used at checkout" /></label>${button('find-order', 'Find order', 'primary')}</form><div id="tracking-result" aria-live="polite"></div></div><div class="track-help"><h3>Need help?</h3><p>Your order number is included in the email confirmation sent after checkout.</p>${routeLink('contact', 'Contact support', 'text-link')}</div></div></section>`; }

export function FaqPage() { return `<section class="page-intro compact"><p class="hero-overline">FAQs</p><h1>Answers, without the runaround.</h1>${Accordion(faqs)}</section>`; }

export function ContactPage() { return `<section class="page-intro compact"><p class="hero-overline">Contact Aura Whey</p><h1>How can we help?</h1><div class="contact-layout"><div><form class="form" data-form="contact"><label class="field">Name<input name="name" placeholder="Your name" /></label><label class="field">Email address<input name="email" type="email" placeholder="you@example.com" /></label><label class="field">Message<textarea name="message" rows="5" placeholder="Tell us how we can help"></textarea></label>${button('send-message', 'Send message', 'primary')}</form><div id="contact-result" aria-live="polite"></div></div><div class="contact-aside"><h3>Before you contact us</h3><p>For an existing order, keep your order number nearby. For product verification, use the code printed on the pack.</p>${routeLink('track-order', 'Track an order', 'text-link')}${routeLink('authenticate', 'Authenticate a pack', 'text-link')}</div></div></section>`; }

export function PolicyPage() { return `<section class="page-intro compact"><p class="hero-overline">Policies</p><h1>Store policies.</h1><div class="policy-grid"><article><h2>Shipping</h2><p>Shipping availability, timelines, and charges are confirmed during Shopify checkout.</p></article><article><h2>Returns</h2><p>Return eligibility is reviewed by support based on the order and product condition.</p></article><article><h2>Privacy</h2><p>Customer information is used to process orders, provide support, and improve the store experience.</p></article></div><p class="small">These policy summaries will be replaced with the approved legal policy text before store launch.</p></section>`; }

export function DocumentPage(state) { return `<section class="page-intro compact"><p class="hero-overline">Quality document</p><h1>${state.document}</h1><div class="document-viewer"><div class="document-sheet"><div class="document-stamp">AW</div><h2>${state.document}</h2><p>This screen is ready to connect to the supplied source PDF when the document library is added to the production store.</p><div class="document-lines"><i></i><i></i><i></i><i></i></div></div><div><p>Use the quality library to browse the supplied certificates for Aura Whey.</p>${routeLink('quality', 'Back to quality documents', 'button-link')}</div></div></section>`; }
